# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- task: DockerInstaller@0 
  displayName: Docker Installer ğŸ“¦
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  displayName: Docker login ğŸ
  inputs:
    script: 'docker login -u 542153354 -p 931592457cz'

- task: CmdLine@2
  displayName: install sshpassâ¤
  inputs:
    script: |
      sudo apt-get install sshpass

- task: Docker@2
  displayName: Docker buildğŸ˜€
  inputs:
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/dockerfile'
    arguments: '-t 542153354/sso:v9.0'

- task: CmdLine@2
  displayName: Docker pushğŸ‘Œ
  inputs:
    script: 'docker push 542153354/sso:v9.0'

- task: CmdLine@2
  displayName: deploy to TencentCloudğŸš€
  inputs:
    script: |
      sshpass -p 931592457czA ssh -o StrictHostKeyChecking=no -t -t ubuntu@119.45.37.57 bash -s < deploy.sh
